-- 2 --
CREATE USER bpb2v IDENTIFIED BY password DEFAULT TABLESPACE USERS TEMPORARY TABLESPACE TEMP;
GRANT CREATE SESSION TO bpb2v WITH ADMIN OPTION;

-- 3 --
GRANT DBA, SYSDBA TO bpb2v;

-- 6 --
ALTER DATABASE ADD supplemental Log data;

-- 7 --
CREATE TABLESPACE bpb2v_space
DATAFILE 'C:\app\OracleOwner\oradata\bb6790\bpb2v_space01.dbf'
SIZE 75M
AUTOALLOCATE
SEGMENT SPACE MANAGEMENT auto;

-- 8 --
ALTER TABLESPACE bpb2v_space
ADD DATAFILE 'C:\app\OracleOwner\oradata\bb6790\bpb2v_space02.dbf'
SIZE 50M;

-- 9 --
CREATE USER NORMALGUY IDENTIFIED BY "password!!" DEFAULT TABLESPACE bpb2v_space TEMPORARY TABLESPACE TEMP;
CREATE USER SUPERGAL IDENTIFIED BY "password!!" DEFAULT TABLESPACE bpb2v_space TEMPORARY TABLESPACE TEMP;
CREATE USER SLBROOKS IDENTIFIED BY password DEFAULT TABLESPACE bpb2v_space TEMPORARY TABLESPACE TEMP;
CREATE USER THATDUDE IDENTIFIED BY password DEFAULT TABLESPACE bpb2v_space TEMPORARY TABLESPACE TEMP;

-- 10 --
CREATE ROLE role6790;
GRANT CONNECT TO role6790;
GRANT RESOURCE TO role6790;
GRANT CREATE SESSION TO role6790;
GRANT CREATE TABLE TO role6790;

-- 11 --
GRANT role6790 TO NORMALGUY;
GRANT role6790 TO SUPERGAL;

-- 12 --
GRANT DBA TO SLBROOKS;
GRANT DBA, SYSDBATO THATDUDE;

-- 13 --
ALTER USER NORMALGUY QUOTA 20M ON USERS QUOTA 30M ON bpb2v_space;
ALTER USER SUPERGAL QUOTA 20M ON USERS QUOTA 30M ON bpb2v_space;

-- 14 --
ALTER PROFILE DEFAULT limit FAILED_LOGIN_ATTEMPTS 4;

-- 15 --
ALTER system SET AUDIT_TRAIL=db,extended scope=spfile;
SELECT name, Value FROM V$PARAMETER WHERE name LIKE 'audit%';

-- 16 --
AUDIT CREATE SESSION BY NORMALGUY;
AUDIT CREATE TABLE BY NORMALGUY;
AUDIT CREATE SESSION BY SUPERGAL;
AUDIT CREATE TABLE BY SUPERGAL;

-- 17 --
AUDIT SELECT ON DEFAULT BY ACCESS;

-- 18 --
CREATE TABLE People(
  Person_ID INT,
  Last_Name VARCHAR(255),
  First_Name VARCHAR(255)
);
INSERT INTO People VALUES(1,'One','First');
INSERT INTO People VALUES(2,'Two','Second');
INSERT INTO People VALUES(3,'Three','Third');
INSERT INTO People VALUES(4,'Four','Fourth');
INSERT INTO People VALUES(5,'Five','Fifth');
SELECT * FROM People;

SELECT username,TIMESTAMP,action_name,sql_text FROM dba_audit_trail ORDER BY timestamp;



DROP TABLE People;
SELECT * FROM dba_audit_trail;
SELECT * FROM sys.aud$;
DELETE FROM sys.aud$ WHERE userid='NORMALGUY';

